---
sidebar: sidebar 
permalink: trident-use/backend_ops_tridentctl.html 
keywords: backends, storage system, anf, element, hci, solidfire, ontap, aff, fas, ontap select, configure backends, tridentctl, create backends, delete backends, view backends, update backends 
summary: 'Erfahren Sie, wie Sie Backend-Verwaltungsvorgänge mithilfe von  `tridentctl` durchführen.' 
---
= Führen Sie die Backend-Verwaltung mit tridentctl durch
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie, wie Sie Backend-Verwaltungsvorgänge mithilfe von  `tridentctl` durchführen.



== Erstelle ein Backend

Nachdem Sie eine link:backends.html["Konfigurationsdatei für das Backend"^] erstellt haben, führen Sie den folgenden Befehl aus:

[listing]
----
tridentctl create backend -f <backend-file> -n trident
----
Wenn die Backend-Erstellung fehlschlägt, gab es ein Problem mit der Backend-Konfiguration. Sie können die Protokolle einsehen, um die Ursache zu ermitteln, indem Sie den folgenden Befehl ausführen:

[listing]
----
tridentctl logs -n trident
----
Nachdem Sie das Problem mit der Konfigurationsdatei identifiziert und behoben haben, können Sie einfach den  `create` Befehl erneut ausführen.



== Ein Backend löschen

Um ein Backend aus Trident zu löschen, gehen Sie wie folgt vor:

. Den Backend-Namen abrufen:
+
[listing]
----
tridentctl get backend -n trident
----
. Backend löschen:
+
[listing]
----
tridentctl delete backend <backend-name> -n trident
----



NOTE: Falls Trident Volumes und Snapshots von diesem Backend bereitgestellt hat, die noch existieren, verhindert das Löschen des Backends, dass neue Volumes von ihm bereitgestellt werden. Das Backend verbleibt im Status „Wird gelöscht“.



== Vorhandene Backends anzeigen

Um die von Trident bekannten Backends anzuzeigen, gehen Sie wie folgt vor:

* Um eine Zusammenfassung zu erhalten, führen Sie den folgenden Befehl aus:
+
[listing]
----
tridentctl get backend -n trident
----
* Um alle Details zu erhalten, führen Sie den folgenden Befehl aus:
+
[listing]
----
tridentctl get backend -o json -n trident
----




== Aktualisieren Sie ein Backend

Nachdem Sie eine neue Backend-Konfigurationsdatei erstellt haben, führen Sie den folgenden Befehl aus:

[listing]
----
tridentctl update backend <backend-name> -f <backend-file> -n trident
----
Wenn die Backend-Aktualisierung fehlschlägt, lag ein Fehler in der Backend-Konfiguration vor oder Sie haben eine ungültige Aktualisierung versucht. Sie können die Protokolle einsehen, um die Ursache zu ermitteln, indem Sie den folgenden Befehl ausführen:

[listing]
----
tridentctl logs -n trident
----
Nachdem Sie das Problem mit der Konfigurationsdatei identifiziert und behoben haben, können Sie einfach den  `update` Befehl erneut ausführen.



== Identifizieren Sie die Speicherklassen, die ein Backend verwenden

Dies ist ein Beispiel für die Art von Fragen, die Sie mit dem JSON, das  `tridentctl` für Backend-Objekte ausgibt, beantworten können. Dies verwendet das  `jq` Hilfsprogramm, das Sie installieren müssen.

[listing]
----
tridentctl get backend -o json | jq '[.items[] | {backend: .name, storageClasses: [.storage[].storageClasses]|unique}]'
----
Dies gilt auch für Backends, die mit  `TridentBackendConfig` erstellt wurden.
