---
sidebar: sidebar 
permalink: trident-concepts/vol-access-groups.html 
keywords: volume access groups, element, solidfire, chap, Trident, hci, netapp hci, storage system, access volumes, 
summary: Erfahren Sie mehr darüber, wie Trident Volumenzugriffsgruppen verwendet. 
---
= Volumenzugriffsgruppen
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Erfahren Sie mehr darüber, wie Trident  https://docs.netapp.com/us-en/element-software/concepts/concept_solidfire_concepts_volume_access_groups.html["Volumenzugriffsgruppen"^] verwendet.


NOTE: Ignorieren Sie diesen Abschnitt, wenn Sie CHAP verwenden, was empfohlen wird, um die Verwaltung zu vereinfachen und die unten beschriebene Skalierungsbeschränkung zu vermeiden. Wenn Sie Trident im CSI-Modus verwenden, können Sie diesen Abschnitt ebenfalls ignorieren. Trident verwendet CHAP, wenn es als erweiterter CSI-Provisioner installiert ist.



== Erfahren Sie mehr über Volumenzugriffsgruppen

Trident kann Volume-Zugriffsgruppen verwenden, um den Zugriff auf die Volumes zu steuern, die es bereitstellt. Wenn CHAP deaktiviert ist, erwartet es, eine Zugriffsgruppe namens  `trident` zu finden, es sei denn, Sie geben eine oder mehrere Zugriffsgruppen-IDs in der Konfiguration an.

Trident ordnet zwar neue Volumes den konfigurierten Zugriffsgruppen zu, erstellt oder verwaltet die Zugriffsgruppen jedoch nicht selbst. Die Zugriffsgruppen müssen existieren, bevor das Speicher-Backend zu Trident hinzugefügt wird, und sie müssen die iSCSI-IQNs von jedem Knoten im Kubernetes-Cluster enthalten, der potenziell die von diesem Backend bereitgestellten Volumes einbinden könnte. In den meisten Installationen umfasst dies alle Worker-Knoten im Cluster.

Für Kubernetes-Cluster mit mehr als 64 Knoten sollten Sie mehrere Zugriffsgruppen verwenden. Jede Zugriffsgruppe kann bis zu 64 IQNs enthalten, und jedes Volume kann zu vier Zugriffsgruppen gehören. Mit den maximal vier konfigurierten Zugriffsgruppen kann jeder Knoten in einem Cluster mit bis zu 256 Knoten auf jedes Volume zugreifen. Die aktuellen Beschränkungen für Volume-Zugriffsgruppen finden Sie unter  https://docs.netapp.com/us-en/element-software/concepts/concept_solidfire_concepts_volume_access_groups.html["hier,"^].

Wenn Sie die Konfiguration von einer, die die Standard `trident` Zugriffsgruppe verwendet, auf eine, die auch andere verwendet, ändern, fügen Sie die ID der  `trident` Zugriffsgruppe in die Liste ein.
